name: CI to Docker Hub
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Create a docker volume
        id: docker_volume
        run: docker volume create dataset

      - name: Run an image for data
        id: docker_run_data
        run: docker run -d --rm --name data_1 -v dataset:/data tzephons/github-action-data

      - name: Run an image for train
        id: docker_run_train
        run: docker run --name train_1 -v dataset:/data tzephons/github-action-train

      - name: Copy model.json from train container
        run: docker cp train_1:/data/model.json ./data/

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/github-action-model:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/github-action-model

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}